example-mermaid:
  files:
    - "src/**/*.hs"

  patterns:
    - pattern: import \?\(qualified\)\? \?\@
      name: module \@

  type: mermaid
  output: "example/out.md"

example-dot:
  files:
    - "src/**/*.hs"

  patterns:
    - pattern: import \(qualified\)\? Depender.\@
      name: module Depender.\@

  type: Dot
  output: example/graph.dot

example-yaml:
  files:
    - "./package.yaml"

  patterns:
    - pattern:
        pattern-type: yaml-parser
        path: .library.dependencies
        iterate-over: array

      name:
        pattern-type: yaml-parser
        path: .name
        iterate-over: string

  type: stdout
  output: example/dependencies.dot
