example-mermaid:
  files:
    - "src/**/*.hs"

  patterns:
    - pattern: import \(qualified \)\?\@
      name: module \@

  type: mermaid
  output: "example/dependencies.md"

example-dot:
  files:
    - "src/**/*.hs"

  patterns:
    - pattern: import \(qualified \)\?Depender.\@
      name: module Depender.\@

  type: Dot
  output: example/local-dependencies.dot

example-yaml:
  files:
    - "./package.yaml"

  patterns:
    - pattern:
        pattern-type: yaml-parser
        path: .library.dependencies
        iterate-over: array

      name:
        pattern-type: yaml-parser
        path: .name
        iterate-over: string

  type: stdout
  output: dummy

example-cpp:
  files:
    - example/**.cpp
    - example/**.hpp

  patterns:
    - pattern: '#include \?"\@"'
      file-name: with-extension

    - pattern: 'using namespace \@;'
      file-name: with-extension

  type: Dot
  output: example/namespaces.dot
