name:                Depender
version:             0.1.0.0
github:              "rihafili/Depender"
license:             BSD3
author:              "Filip Říha"
maintainer:          "rihafili@fit.cvut.cz"
copyright:           "MIT"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Highly customisable dependency graph generator
# category:            Dependency visualization

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rihafili/Depender#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - yaml
  - text
  - filepath
  - directory
  - containers
  - aeson
  - aeson-combinators
  - vector
  - bytestring
  - rainbow
  - cmdargs

executables:
  Depender-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Depender

tests:
  Depender-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Depender
    - doctest
    - hspec
    - filepath
    - raw-strings-qq
    - yaml
    - aeson-combinators
    - bytestring
